AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Luckuy pick serverless

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: API gateway for lucky pick
      StageName: dev

  LuckyPickLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-dependencies
      Description: Dependencies for lucky-pick
      ContentUri: ../dependencies/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  LuckyPickFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist-server/
      Handler: lambda.fulfillment
      Runtime: nodejs12.x
      Timeout: 15
      Layers:
        - !Ref LuckyPickLayer
      Events:
        LuckyPickApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /webhook
            Method: POST

Outputs:
  BasicAWSApiGateway:
    Description: 'API Gateway endpoint URL for Staging stage for Hello World function'
    Value: !Sub 'https://${BasicAWSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/webhook/'
  BasicAWSApiGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref BasicAWSApiGateway
    Export:
      Name: BasicAWSApiGateway-RestApiId
  BasicAWSApiGatewayRootResourceId:
    Value: !GetAtt BasicAWSApiGateway.RootResourceId
    Export:
      Name: BasicAWSApiGateway-RootResourceId
